#     server/
#     │
#     ├── Dockerfile
#     ├── requirements.txt
#     ├── etc/
#     │   └── shadow/
#     │       ├── client_public.pem
#     │       ├── server_private.pem
#     │       └── user_credentials.json
#     ├── admin_portal.py
#     └── server_script.py

# Use an official Python runtime as a parent image
FROM python

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Make port 55555 available to the world outside this container
EXPOSE 55555

# Define environment variable
ENV PYTHONUNBUFFERED=1

# Run server_script.py when the container launches
CMD ["python3", "./server.py"]
